### ISSUE TITLE
Error when opening a custom Objects Journal Tab

### ISSUE THREAD

**Issue by joshuahornig** [netboxlabs/netbox-custom-objects#413]
### Plugin Version

0.4.6

### NetBox Version

4.5.4

### Python Version

3.12.12

### Steps to Reproduce

1. create  a custom object
2. go on Journal Tab

was Working on 4.4.9

### Expected Behavior

no Error

### Observed Behavior

he complete exception is provided below:

<class 'TypeError'>

Table.__init__() got an unexpected keyword argument 'user'

Python version: 3.12.12
NetBox version: 4.5.4
Plugins: 
  netbox_custom_objects: 0.4.6
  netbox_dns: 1.5.3
The request which yielded the above error is shown below:
